# Generated by Django 2.0.3 on 2018-09-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64, null=True)),
                ('house_no', models.SmallIntegerField()),
                ('flat_no', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('email_type', models.IntegerField(choices=[(0, 'nie zdefiniowany'), (1, 'prywatny'), (2, 'służbowy'), (3, 'inny')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail_box.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
                ('no_type', models.IntegerField(choices=[(0, 'nie zdefiniowany'), (1, 'prywatny'), (2, 'służbowy'), (3, 'inny')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_box.Person')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='person',
            field=models.ManyToManyField(to='mail_box.Person'),
        ),
        migrations.AddField(
            model_name='email',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_box.Person'),
        ),
    ]
